### ISSUE TITLE
Night elf race abils

### ISSUE THREAD

**Issue by neuromagus** [dalaranwow/issue-tracker#7] opened 2022-08-21 17:40 UTC
Shadowmelt not work properly. Monsters stay in fight and did not lose focus. Well, this is my last issue, I think I'm done with this area. 

Best regards, Dalaran team.

**Comment by Lothloryen** [comment] 2022-09-08 13:50
Greetings,

Thank you for the report. However, shadowmeld works as intended, so closing this issue.

**Closed as completed by Lothloryen** 2022-09-08 13:50 UTC
